package com.ml.entities;

// Generated 2016-4-1 18:42:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission")
public class Permission implements java.io.Serializable {

    private String perId;
    private PermissionGroup permissionGroup;
    private String name;
    private String description;
    private Integer system_code;
    private Set<RolePermission> rolePermissions = new HashSet<>(0);

    public Permission() {
    }

    public Permission(String perId) {
        this.perId = perId;
    }

    public Permission(String perId, PermissionGroup permissionGroup, String name, String description, Set<RolePermission> rolePermissions) {
        this.perId = perId;
        this.permissionGroup = permissionGroup;
        this.name = name;
        this.description = description;
        this.rolePermissions = rolePermissions;
    }

    @Id
    @Column(name = "per_id", unique = true, nullable = false, length = 36)
    public String getPerId() {
        return this.perId;
    }

    public void setPerId(String perId) {
        this.perId = perId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "group_id")
    public PermissionGroup getPermissionGroup() {
        return this.permissionGroup;
    }

    public void setPermissionGroup(PermissionGroup permissionGroup) {
        this.permissionGroup = permissionGroup;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 200)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "system_code")
    public Integer getSystem_code() {
        return system_code;
    }

    public void setSystem_code(Integer system_code) {
        this.system_code = system_code;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
    public Set<RolePermission> getRolePermissions() {
        return this.rolePermissions;
    }

    public void setRolePermissions(Set<RolePermission> rolePermissions) {
        this.rolePermissions = rolePermissions;
    }

}
