package com.ml.entities;

// Generated 2017-2-24 16:03:26 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourceRoleId generated by hbm2java
 */
@Embeddable
public class ResourceRoleId implements java.io.Serializable {

	private Long rescId;
	private Long roleId;

	public ResourceRoleId() {
	}

	public ResourceRoleId(Long rescId, Long roleId) {
		this.rescId = rescId;
		this.roleId = roleId;
	}

	@Column(name = "resc_id")
	public Long getRescId() {
		return this.rescId;
	}

	public void setRescId(Long rescId) {
		this.rescId = rescId;
	}

	@Column(name = "role_id")
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourceRoleId))
			return false;
		ResourceRoleId castOther = (ResourceRoleId) other;

		return ((this.getRescId() == castOther.getRescId()) || (this
				.getRescId() != null && castOther.getRescId() != null && this
				.getRescId().equals(castOther.getRescId())))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this
						.getRoleId() != null && castOther.getRoleId() != null && this
						.getRoleId().equals(castOther.getRoleId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRescId() == null ? 0 : this.getRescId().hashCode());
		result = 37 * result
				+ (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		return result;
	}

}
