package com.ml.entities;

// Generated 2017-2-24 16:03:26 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "security")
public class Resource implements java.io.Serializable {

    private Long id;
    private String name;
    private String resType;
    private String resString;
    private Integer priority;
    private String desc;
    private Set<ResourceRole> resourceRoles = new HashSet<ResourceRole>(0);

    public Resource() {
    }

    public Resource(String name, String resType, String resString, Integer priority, String desc, Set<ResourceRole> resourceRoles) {
        this.name = name;
        this.resType = resType;
        this.resString = resString;
        this.priority = priority;
        this.desc = desc;
        this.resourceRoles = resourceRoles;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "res_type", length = 50)
    public String getResType() {
        return this.resType;
    }

    public void setResType(String resType) {
        this.resType = resType;
    }

    @Column(name = "res_string", length = 200)
    public String getResString() {
        return this.resString;
    }

    public void setResString(String resString) {
        this.resString = resString;
    }

    @Column(name = "priority")
    public Integer getPriority() {
        return this.priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @Column(name = "desc", length = 200)
    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
    public Set<ResourceRole> getResourceRoles() {
        return this.resourceRoles;
    }

    public void setResourceRoles(Set<ResourceRole> resourceRoles) {
        this.resourceRoles = resourceRoles;
    }

}
