package com.ml.entities;

// Generated 2017-2-24 16:03:26 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourceRole generated by hbm2java
 */
@Entity
@Table(name = "resource_role", catalog = "security")
public class ResourceRole implements java.io.Serializable {

	private ResourceRoleId id;
	private Resource resource;
	private Role role;

	public ResourceRole() {
	}

	public ResourceRole(ResourceRoleId id) {
		this.id = id;
	}

	public ResourceRole(ResourceRoleId id, Resource resource, Role role) {
		this.id = id;
		this.resource = resource;
		this.role = role;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rescId", column = @Column(name = "resc_id")),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id")) })
	public ResourceRoleId getId() {
		return this.id;
	}

	public void setId(ResourceRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resc_id", insertable = false, updatable = false)
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
