package com.ml.entities;

// Generated 2017-2-23 18:06:43 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "shiro")
public class Resource implements java.io.Serializable {

	private Long id;
	private String name;
	private String url;
	private String openMode;
	private String description;
	private String icon;
	private Long pid;
	private byte seq;
	private byte status;
	private byte opened;
	private byte resourceType;
	private Date createTime;
	private Set<RoleResource> roleResources = new HashSet<RoleResource>(0);

	public Resource() {
	}

	public Resource(String name, byte seq, byte status, byte opened,
			byte resourceType, Date createTime) {
		this.name = name;
		this.seq = seq;
		this.status = status;
		this.opened = opened;
		this.resourceType = resourceType;
		this.createTime = createTime;
	}

	public Resource(String name, String url, String openMode,
			String description, String icon, Long pid, byte seq, byte status,
			byte opened, byte resourceType, Date createTime,
			Set<RoleResource> roleResources) {
		this.name = name;
		this.url = url;
		this.openMode = openMode;
		this.description = description;
		this.icon = icon;
		this.pid = pid;
		this.seq = seq;
		this.status = status;
		this.opened = opened;
		this.resourceType = resourceType;
		this.createTime = createTime;
		this.roleResources = roleResources;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "open_mode", length = 32)
	public String getOpenMode() {
		return this.openMode;
	}

	public void setOpenMode(String openMode) {
		this.openMode = openMode;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "icon", length = 32)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "pid")
	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	@Column(name = "seq", nullable = false)
	public byte getSeq() {
		return this.seq;
	}

	public void setSeq(byte seq) {
		this.seq = seq;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "opened", nullable = false)
	public byte getOpened() {
		return this.opened;
	}

	public void setOpened(byte opened) {
		this.opened = opened;
	}

	@Column(name = "resource_type", nullable = false)
	public byte getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(byte resourceType) {
		this.resourceType = resourceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<RoleResource> getRoleResources() {
		return this.roleResources;
	}

	public void setRoleResources(Set<RoleResource> roleResources) {
		this.roleResources = roleResources;
	}

}
