package com.ml.entities;

// Generated 2016-4-1 18:42:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePermissionId generated by hbm2java
 */
@SuppressWarnings("StringEquality")
@Embeddable
public class RolePermissionId implements java.io.Serializable {

	private String roleId;
	private String perId;

	public RolePermissionId() {
	}

	public RolePermissionId(String roleId, String perId) {
		this.roleId = roleId;
		this.perId = perId;
	}

	@Column(name = "role_id", nullable = false, length = 36)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "per_id", nullable = false, length = 36)
	public String getPerId() {
		return this.perId;
	}

	public void setPerId(String perId) {
		this.perId = perId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePermissionId))
			return false;
		RolePermissionId castOther = (RolePermissionId) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null && castOther.getRoleId() != null && this.getRoleId().equals(
				castOther.getRoleId())))
				&& ((this.getPerId() == castOther.getPerId()) || (this.getPerId() != null && castOther.getPerId() != null && this.getPerId().equals(
						castOther.getPerId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getPerId() == null ? 0 : this.getPerId().hashCode());
		return result;
	}

}
