package com.ml.entities;

// Generated 2016-4-1 18:42:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "role_permission")
public class RolePermission implements java.io.Serializable {

	private RolePermissionId id;
	private Role role;
	private Permission permission;

	public RolePermission() {
	}

	public RolePermission(RolePermissionId id, Role role, Permission permission) {
		this.id = id;
		this.role = role;
		this.permission = permission;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false, length = 36)),
			@AttributeOverride(name = "perId", column = @Column(name = "per_id", nullable = false, length = 36)) })
	public RolePermissionId getId() {
		return this.id;
	}

	public void setId(RolePermissionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "per_id", nullable = false, insertable = false, updatable = false)
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

}
